variable "aws_region"          { default = "ap-south-1" }
variable "project_name"        { default = "hotstar-clone-devsecops" }
variable "vpc_cidr"            { default = "10.0.0.0/16" }
variable "availability_zones"  { default = ["ap-south-1a", "ap-south-1b", "ap-south-1c"] }
variable "private_subnets"     { default = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"] }
variable "public_subnets"      { default = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"] }
variable "eks_cluster_version" { default = "1.30" }
variable "node_instance_types" { default = ["c7i-flex.large"] }
variable "node_group_min"      { default = 1 }
variable "node_group_max"      { default = 4 }
variable "node_group_desired"  { default = 2 }
